--
-- PostgreSQL database dump
--

-- Dumped from database version 17.2
-- Dumped by pg_dump version 17.2

-- Started on 2025-04-10 16:53:22

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 253 (class 1259 OID 27083)
-- Name: auth_group; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO gisuser;

--
-- TOC entry 252 (class 1259 OID 27082)
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 255 (class 1259 OID 27091)
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO gisuser;

--
-- TOC entry 254 (class 1259 OID 27090)
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 251 (class 1259 OID 27077)
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO gisuser;

--
-- TOC entry 250 (class 1259 OID 27076)
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 257 (class 1259 OID 27097)
-- Name: auth_user; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO gisuser;

--
-- TOC entry 259 (class 1259 OID 27105)
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO gisuser;

--
-- TOC entry 258 (class 1259 OID 27104)
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 256 (class 1259 OID 27096)
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 261 (class 1259 OID 27111)
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO gisuser;

--
-- TOC entry 260 (class 1259 OID 27110)
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 227 (class 1259 OID 26933)
-- Name: bank; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bank (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    name character varying(100),
    geom public.geometry(Point,4326)
);


ALTER TABLE public.bank OWNER TO postgres;

--
-- TOC entry 226 (class 1259 OID 26932)
-- Name: bank_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bank_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.bank_gid_seq OWNER TO postgres;

--
-- TOC entry 6630 (class 0 OID 0)
-- Dependencies: 226
-- Name: bank_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.bank_gid_seq OWNED BY public.bank.gid;


--
-- TOC entry 229 (class 1259 OID 26944)
-- Name: bus_stops; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.bus_stops (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    name character varying(100),
    geom public.geometry(Point,4326)
);


ALTER TABLE public.bus_stops OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 26943)
-- Name: bus_stops_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.bus_stops_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.bus_stops_gid_seq OWNER TO postgres;

--
-- TOC entry 6633 (class 0 OID 0)
-- Dependencies: 228
-- Name: bus_stops_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.bus_stops_gid_seq OWNED BY public.bus_stops.gid;


--
-- TOC entry 263 (class 1259 OID 27169)
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO gisuser;

--
-- TOC entry 262 (class 1259 OID 27168)
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 249 (class 1259 OID 27069)
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO gisuser;

--
-- TOC entry 248 (class 1259 OID 27068)
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 247 (class 1259 OID 27061)
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO gisuser;

--
-- TOC entry 246 (class 1259 OID 27060)
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 270 (class 1259 OID 27224)
-- Name: django_session; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO gisuser;

--
-- TOC entry 265 (class 1259 OID 27198)
-- Name: gisapp_healthcare; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.gisapp_healthcare (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    geom public.geometry(Point,4326) NOT NULL
);


ALTER TABLE public.gisapp_healthcare OWNER TO gisuser;

--
-- TOC entry 264 (class 1259 OID 27197)
-- Name: gisapp_healthcare_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.gisapp_healthcare ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gisapp_healthcare_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 267 (class 1259 OID 27206)
-- Name: gisapp_islamabadboundary; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.gisapp_islamabadboundary (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    geom public.geometry(Polygon,4326) NOT NULL
);


ALTER TABLE public.gisapp_islamabadboundary OWNER TO gisuser;

--
-- TOC entry 266 (class 1259 OID 27205)
-- Name: gisapp_islamabadboundary_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.gisapp_islamabadboundary ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gisapp_islamabadboundary_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 269 (class 1259 OID 27214)
-- Name: gisapp_school; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.gisapp_school (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    geom public.geometry(Point,4326) NOT NULL
);


ALTER TABLE public.gisapp_school OWNER TO gisuser;

--
-- TOC entry 268 (class 1259 OID 27213)
-- Name: gisapp_school_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.gisapp_school ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gisapp_school_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 231 (class 1259 OID 26955)
-- Name: healthcare; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.healthcare (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    name character varying(100),
    geom public.geometry(Point,4326)
);


ALTER TABLE public.healthcare OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 26954)
-- Name: healthcare_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.healthcare_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.healthcare_gid_seq OWNER TO postgres;

--
-- TOC entry 6636 (class 0 OID 0)
-- Dependencies: 230
-- Name: healthcare_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.healthcare_gid_seq OWNED BY public.healthcare.gid;


--
-- TOC entry 300 (class 1259 OID 36846)
-- Name: healthcare_raster; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.healthcare_raster (
    rast public.raster
);


ALTER TABLE public.healthcare_raster OWNER TO gisuser;

--
-- TOC entry 233 (class 1259 OID 26966)
-- Name: helipad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.helipad (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    name character varying(100),
    geom public.geometry(Point,4326)
);


ALTER TABLE public.helipad OWNER TO postgres;

--
-- TOC entry 232 (class 1259 OID 26965)
-- Name: helipad_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.helipad_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.helipad_gid_seq OWNER TO postgres;

--
-- TOC entry 6639 (class 0 OID 0)
-- Dependencies: 232
-- Name: helipad_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.helipad_gid_seq OWNED BY public.helipad.gid;


--
-- TOC entry 235 (class 1259 OID 26976)
-- Name: islamabad; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.islamabad (
    gid integer NOT NULL,
    shape_leng numeric,
    shape_area numeric,
    adm3_en character varying(50),
    adm3_pcode character varying(50),
    adm3_ref character varying(50),
    adm3alt1en character varying(50),
    adm3alt2en character varying(50),
    adm2_en character varying(50),
    adm2_pcode character varying(50),
    adm1_en character varying(50),
    adm1_pcode character varying(50),
    adm0_en character varying(50),
    adm0_pcode character varying(50),
    date date,
    validon date,
    validto date,
    geom public.geometry(MultiPolygon,4326)
);


ALTER TABLE public.islamabad OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 26975)
-- Name: islamabad_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.islamabad_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.islamabad_gid_seq OWNER TO postgres;

--
-- TOC entry 6642 (class 0 OID 0)
-- Dependencies: 234
-- Name: islamabad_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.islamabad_gid_seq OWNED BY public.islamabad.gid;


--
-- TOC entry 296 (class 1259 OID 36576)
-- Name: landuse; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.landuse (
    rid integer NOT NULL,
    rast public.raster,
    filename text,
    CONSTRAINT enforce_height_rast CHECK ((public.st_height(rast) = ANY (ARRAY[128, 88]))),
    CONSTRAINT enforce_nodata_values_rast CHECK ((public._raster_constraint_nodata_values(rast) = '{0.0000000000}'::numeric[])),
    CONSTRAINT enforce_num_bands_rast CHECK ((public.st_numbands(rast) = 1)),
    CONSTRAINT enforce_out_db_rast CHECK ((public._raster_constraint_out_db(rast) = '{f}'::boolean[])),
    CONSTRAINT enforce_pixel_types_rast CHECK ((public._raster_constraint_pixel_types(rast) = '{8BUI}'::text[])),
    CONSTRAINT enforce_same_alignment_rast CHECK (public.st_samealignment(rast, '0100000000A5280D8EFBFF2340B7280D8EFBFF23C00C9E6154EEFE13419A3C242D6E8F4C4100000000000000000000000000000000E610000001000100'::public.raster)),
    CONSTRAINT enforce_scalex_rast CHECK ((round((public.st_scalex(rast))::numeric, 10) = round(9.999966086489005, 10))),
    CONSTRAINT enforce_scaley_rast CHECK ((round((public.st_scaley(rast))::numeric, 10) = round((- 9.999966086489037), 10))),
    CONSTRAINT enforce_srid_rast CHECK ((public.st_srid(rast) = 4326)),
    CONSTRAINT enforce_width_rast CHECK ((public.st_width(rast) = ANY (ARRAY[128, 28])))
);


ALTER TABLE public.landuse OWNER TO gisuser;

--
-- TOC entry 295 (class 1259 OID 36575)
-- Name: landuse_rid_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

CREATE SEQUENCE public.landuse_rid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.landuse_rid_seq OWNER TO gisuser;

--
-- TOC entry 6644 (class 0 OID 0)
-- Dependencies: 295
-- Name: landuse_rid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: gisuser
--

ALTER SEQUENCE public.landuse_rid_seq OWNED BY public.landuse.rid;


--
-- TOC entry 272 (class 1259 OID 27234)
-- Name: maps_bank; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.maps_bank (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    geom public.geometry(Point,4326) NOT NULL
);


ALTER TABLE public.maps_bank OWNER TO gisuser;

--
-- TOC entry 271 (class 1259 OID 27233)
-- Name: maps_bank_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.maps_bank ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maps_bank_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 274 (class 1259 OID 27242)
-- Name: maps_bus_stops; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.maps_bus_stops (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    geom public.geometry(Point,4326) NOT NULL
);


ALTER TABLE public.maps_bus_stops OWNER TO gisuser;

--
-- TOC entry 273 (class 1259 OID 27241)
-- Name: maps_bus_stops_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.maps_bus_stops ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maps_bus_stops_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 276 (class 1259 OID 27250)
-- Name: maps_healthcare; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.maps_healthcare (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    geom public.geometry(Point,4326) NOT NULL
);


ALTER TABLE public.maps_healthcare OWNER TO gisuser;

--
-- TOC entry 275 (class 1259 OID 27249)
-- Name: maps_healthcare_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.maps_healthcare ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maps_healthcare_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 278 (class 1259 OID 27258)
-- Name: maps_islamabad; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.maps_islamabad (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    geom public.geometry(Polygon,4326) NOT NULL
);


ALTER TABLE public.maps_islamabad OWNER TO gisuser;

--
-- TOC entry 277 (class 1259 OID 27257)
-- Name: maps_islamabad_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.maps_islamabad ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maps_islamabad_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 280 (class 1259 OID 27266)
-- Name: maps_masjids; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.maps_masjids (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    geom public.geometry(Point,4326) NOT NULL
);


ALTER TABLE public.maps_masjids OWNER TO gisuser;

--
-- TOC entry 279 (class 1259 OID 27265)
-- Name: maps_masjids_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.maps_masjids ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maps_masjids_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 282 (class 1259 OID 27274)
-- Name: maps_railway_station; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.maps_railway_station (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    geom public.geometry(Point,4326) NOT NULL
);


ALTER TABLE public.maps_railway_station OWNER TO gisuser;

--
-- TOC entry 281 (class 1259 OID 27273)
-- Name: maps_railway_station_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.maps_railway_station ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maps_railway_station_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 284 (class 1259 OID 27282)
-- Name: maps_schoolst; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.maps_schoolst (
    id bigint NOT NULL,
    name character varying(255) NOT NULL,
    geom public.geometry(Point,4326) NOT NULL
);


ALTER TABLE public.maps_schoolst OWNER TO gisuser;

--
-- TOC entry 283 (class 1259 OID 27281)
-- Name: maps_schoolst_id_seq; Type: SEQUENCE; Schema: public; Owner: gisuser
--

ALTER TABLE public.maps_schoolst ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.maps_schoolst_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 237 (class 1259 OID 26987)
-- Name: masjids; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.masjids (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    name character varying(100),
    geom public.geometry(Point,4326)
);


ALTER TABLE public.masjids OWNER TO postgres;

--
-- TOC entry 236 (class 1259 OID 26986)
-- Name: masjids_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.masjids_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.masjids_gid_seq OWNER TO postgres;

--
-- TOC entry 6646 (class 0 OID 0)
-- Dependencies: 236
-- Name: masjids_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.masjids_gid_seq OWNED BY public.masjids.gid;


--
-- TOC entry 301 (class 1259 OID 36867)
-- Name: masjids_raster; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.masjids_raster (
    rast public.raster
);


ALTER TABLE public.masjids_raster OWNER TO gisuser;

--
-- TOC entry 239 (class 1259 OID 26998)
-- Name: pois; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pois (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    name character varying(100),
    geom public.geometry(Point)
);


ALTER TABLE public.pois OWNER TO postgres;

--
-- TOC entry 238 (class 1259 OID 26997)
-- Name: pois_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.pois_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.pois_gid_seq OWNER TO postgres;

--
-- TOC entry 6649 (class 0 OID 0)
-- Dependencies: 238
-- Name: pois_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.pois_gid_seq OWNED BY public.pois.gid;


--
-- TOC entry 305 (class 1259 OID 43520)
-- Name: railway; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.railway (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    name character varying(100),
    layer double precision,
    bridge character varying(1),
    tunnel character varying(1),
    geom public.geometry(MultiLineString,4326)
);


ALTER TABLE public.railway OWNER TO postgres;

--
-- TOC entry 304 (class 1259 OID 43519)
-- Name: railway_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.railway_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.railway_gid_seq OWNER TO postgres;

--
-- TOC entry 6652 (class 0 OID 0)
-- Dependencies: 304
-- Name: railway_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.railway_gid_seq OWNED BY public.railway.gid;


--
-- TOC entry 241 (class 1259 OID 27012)
-- Name: railway_station; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.railway_station (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    name character varying(100),
    geom public.geometry(Point,4326)
);


ALTER TABLE public.railway_station OWNER TO postgres;

--
-- TOC entry 240 (class 1259 OID 27011)
-- Name: railway_station_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.railway_station_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.railway_station_gid_seq OWNER TO postgres;

--
-- TOC entry 6654 (class 0 OID 0)
-- Dependencies: 240
-- Name: railway_station_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.railway_station_gid_seq OWNED BY public.railway_station.gid;


--
-- TOC entry 307 (class 1259 OID 43531)
-- Name: roads; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.roads (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    name character varying(100),
    ref character varying(20),
    oneway character varying(1),
    maxspeed smallint,
    layer double precision,
    bridge character varying(1),
    tunnel character varying(1),
    geom public.geometry(MultiLineString,4326)
);


ALTER TABLE public.roads OWNER TO postgres;

--
-- TOC entry 306 (class 1259 OID 43530)
-- Name: roads_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.roads_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.roads_gid_seq OWNER TO postgres;

--
-- TOC entry 6657 (class 0 OID 0)
-- Dependencies: 306
-- Name: roads_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.roads_gid_seq OWNED BY public.roads.gid;


--
-- TOC entry 243 (class 1259 OID 27022)
-- Name: schools; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.schools (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    name character varying(100),
    geom public.geometry(Point,4326)
);


ALTER TABLE public.schools OWNER TO postgres;

--
-- TOC entry 242 (class 1259 OID 27021)
-- Name: schoolst_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.schoolst_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.schoolst_gid_seq OWNER TO postgres;

--
-- TOC entry 6659 (class 0 OID 0)
-- Dependencies: 242
-- Name: schoolst_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.schoolst_gid_seq OWNED BY public.schools.gid;


--
-- TOC entry 298 (class 1259 OID 36728)
-- Name: slope; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.slope (
    rid integer NOT NULL,
    rast public.raster,
    filename text,
    CONSTRAINT enforce_height_rast CHECK ((public.st_height(rast) = ANY (ARRAY[128, 88]))),
    CONSTRAINT enforce_nodata_values_rast CHECK ((public._raster_constraint_nodata_values(rast) = '{0.0000000000}'::numeric[])),
    CONSTRAINT enforce_num_bands_rast CHECK ((public.st_numbands(rast) = 1)),
    CONSTRAINT enforce_out_db_rast CHECK ((public._raster_constraint_out_db(rast) = '{f}'::boolean[])),
    CONSTRAINT enforce_pixel_types_rast CHECK ((public._raster_constraint_pixel_types(rast) = '{8BUI}'::text[])),
    CONSTRAINT enforce_same_alignment_rast CHECK (public.st_samealignment(rast, '0100000000A5280D8EFBFF2340B7280D8EFBFF23C00C9E6154EEFE13419A3C242D6E8F4C4100000000000000000000000000000000E610000001000100'::public.raster)),
    CONSTRAINT enforce_scalex_rast CHECK ((round((public.st_scalex(rast))::numeric, 10) = round(9.999966086489005, 10))),
    CONSTRAINT enforce_scaley_rast CHECK ((round((public.st_scaley(rast))::numeric, 10) = round((- 9.999966086489037), 10))),
    CONSTRAINT enforce_srid_rast CHECK ((public.st_srid(rast) = 4326)),
    CONSTRAINT enforce_width_rast CHECK ((public.st_width(rast) = ANY (ARRAY[128, 28])))
);


ALTER TABLE public.slope OWNER TO postgres;

--
-- TOC entry 297 (class 1259 OID 36727)
-- Name: slope_rid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.slope_rid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.slope_rid_seq OWNER TO postgres;

--
-- TOC entry 6662 (class 0 OID 0)
-- Dependencies: 297
-- Name: slope_rid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.slope_rid_seq OWNED BY public.slope.rid;


--
-- TOC entry 299 (class 1259 OID 36794)
-- Name: temp_raster; Type: TABLE; Schema: public; Owner: gisuser
--

CREATE TABLE public.temp_raster (
    rast public.raster
);


ALTER TABLE public.temp_raster OWNER TO gisuser;

--
-- TOC entry 245 (class 1259 OID 27034)
-- Name: transport; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.transport (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    name character varying(100),
    geom public.geometry(Point,4326)
);


ALTER TABLE public.transport OWNER TO postgres;

--
-- TOC entry 244 (class 1259 OID 27033)
-- Name: transport_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.transport_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.transport_gid_seq OWNER TO postgres;

--
-- TOC entry 6664 (class 0 OID 0)
-- Dependencies: 244
-- Name: transport_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.transport_gid_seq OWNED BY public.transport.gid;


--
-- TOC entry 303 (class 1259 OID 43507)
-- Name: waters; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.waters (
    gid integer NOT NULL,
    osm_id character varying(12),
    code smallint,
    fclass character varying(28),
    width integer,
    name character varying(100),
    geom public.geometry(MultiLineString,4326)
);


ALTER TABLE public.waters OWNER TO postgres;

--
-- TOC entry 302 (class 1259 OID 43506)
-- Name: waters_gid_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.waters_gid_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE public.waters_gid_seq OWNER TO postgres;

--
-- TOC entry 6667 (class 0 OID 0)
-- Dependencies: 302
-- Name: waters_gid_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.waters_gid_seq OWNED BY public.waters.gid;


--
-- TOC entry 6300 (class 2604 OID 26936)
-- Name: bank gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bank ALTER COLUMN gid SET DEFAULT nextval('public.bank_gid_seq'::regclass);


--
-- TOC entry 6301 (class 2604 OID 26947)
-- Name: bus_stops gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bus_stops ALTER COLUMN gid SET DEFAULT nextval('public.bus_stops_gid_seq'::regclass);


--
-- TOC entry 6302 (class 2604 OID 26958)
-- Name: healthcare gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.healthcare ALTER COLUMN gid SET DEFAULT nextval('public.healthcare_gid_seq'::regclass);


--
-- TOC entry 6303 (class 2604 OID 26969)
-- Name: helipad gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.helipad ALTER COLUMN gid SET DEFAULT nextval('public.helipad_gid_seq'::regclass);


--
-- TOC entry 6304 (class 2604 OID 26979)
-- Name: islamabad gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.islamabad ALTER COLUMN gid SET DEFAULT nextval('public.islamabad_gid_seq'::regclass);


--
-- TOC entry 6310 (class 2604 OID 36579)
-- Name: landuse rid; Type: DEFAULT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.landuse ALTER COLUMN rid SET DEFAULT nextval('public.landuse_rid_seq'::regclass);


--
-- TOC entry 6305 (class 2604 OID 26990)
-- Name: masjids gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.masjids ALTER COLUMN gid SET DEFAULT nextval('public.masjids_gid_seq'::regclass);


--
-- TOC entry 6306 (class 2604 OID 27001)
-- Name: pois gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pois ALTER COLUMN gid SET DEFAULT nextval('public.pois_gid_seq'::regclass);


--
-- TOC entry 6313 (class 2604 OID 43523)
-- Name: railway gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.railway ALTER COLUMN gid SET DEFAULT nextval('public.railway_gid_seq'::regclass);


--
-- TOC entry 6307 (class 2604 OID 27015)
-- Name: railway_station gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.railway_station ALTER COLUMN gid SET DEFAULT nextval('public.railway_station_gid_seq'::regclass);


--
-- TOC entry 6314 (class 2604 OID 43534)
-- Name: roads gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roads ALTER COLUMN gid SET DEFAULT nextval('public.roads_gid_seq'::regclass);


--
-- TOC entry 6308 (class 2604 OID 27025)
-- Name: schools gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schools ALTER COLUMN gid SET DEFAULT nextval('public.schoolst_gid_seq'::regclass);


--
-- TOC entry 6311 (class 2604 OID 36731)
-- Name: slope rid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slope ALTER COLUMN rid SET DEFAULT nextval('public.slope_rid_seq'::regclass);


--
-- TOC entry 6309 (class 2604 OID 27037)
-- Name: transport gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transport ALTER COLUMN gid SET DEFAULT nextval('public.transport_gid_seq'::regclass);


--
-- TOC entry 6312 (class 2604 OID 43510)
-- Name: waters gid; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waters ALTER COLUMN gid SET DEFAULT nextval('public.waters_gid_seq'::regclass);


--
-- TOC entry 6384 (class 2606 OID 27195)
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- TOC entry 6389 (class 2606 OID 27126)
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- TOC entry 6392 (class 2606 OID 27095)
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 6386 (class 2606 OID 27087)
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- TOC entry 6379 (class 2606 OID 27117)
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- TOC entry 6381 (class 2606 OID 27081)
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- TOC entry 6400 (class 2606 OID 27109)
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- TOC entry 6403 (class 2606 OID 27141)
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- TOC entry 6394 (class 2606 OID 27101)
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- TOC entry 6406 (class 2606 OID 27115)
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- TOC entry 6409 (class 2606 OID 27155)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- TOC entry 6397 (class 2606 OID 27190)
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- TOC entry 6343 (class 2606 OID 26938)
-- Name: bank bank_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bank
    ADD CONSTRAINT bank_pkey PRIMARY KEY (gid);


--
-- TOC entry 6346 (class 2606 OID 26949)
-- Name: bus_stops bus_stops_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.bus_stops
    ADD CONSTRAINT bus_stops_pkey PRIMARY KEY (gid);


--
-- TOC entry 6412 (class 2606 OID 27176)
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- TOC entry 6374 (class 2606 OID 27075)
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- TOC entry 6376 (class 2606 OID 27073)
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- TOC entry 6372 (class 2606 OID 27067)
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- TOC entry 6425 (class 2606 OID 27230)
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- TOC entry 6318 (class 2606 OID 36601)
-- Name: landuse enforce_max_extent_rast; Type: CHECK CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE public.landuse
    ADD CONSTRAINT enforce_max_extent_rast CHECK ((public.st_envelope(rast) OPERATOR(public.@) '0103000020E610000001000000050000003C6210BFEE1E12416BD9143DB6474C413C6210BFEE1E12419A3C242D6E8F4C41C89D65034E6B15419A3C242D6E8F4C41C89D65034E6B15416BD9143DB6474C413C6210BFEE1E12416BD9143DB6474C41'::public.geometry)) NOT VALID;


--
-- TOC entry 6329 (class 2606 OID 36753)
-- Name: slope enforce_max_extent_rast; Type: CHECK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE public.slope
    ADD CONSTRAINT enforce_max_extent_rast CHECK ((public.st_envelope(rast) OPERATOR(public.@) '0103000020E610000001000000050000003C6210BFEE1E12416BD9143DB6474C413C6210BFEE1E12419A3C242D6E8F4C41C89D65034E6B15419A3C242D6E8F4C41C89D65034E6B15416BD9143DB6474C413C6210BFEE1E12416BD9143DB6474C41'::public.geometry)) NOT VALID;


--
-- TOC entry 6416 (class 2606 OID 27204)
-- Name: gisapp_healthcare gisapp_healthcare_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.gisapp_healthcare
    ADD CONSTRAINT gisapp_healthcare_pkey PRIMARY KEY (id);


--
-- TOC entry 6419 (class 2606 OID 27212)
-- Name: gisapp_islamabadboundary gisapp_islamabadboundary_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.gisapp_islamabadboundary
    ADD CONSTRAINT gisapp_islamabadboundary_pkey PRIMARY KEY (id);


--
-- TOC entry 6422 (class 2606 OID 27220)
-- Name: gisapp_school gisapp_school_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.gisapp_school
    ADD CONSTRAINT gisapp_school_pkey PRIMARY KEY (id);


--
-- TOC entry 6349 (class 2606 OID 26960)
-- Name: healthcare healthcare_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.healthcare
    ADD CONSTRAINT healthcare_pkey PRIMARY KEY (gid);


--
-- TOC entry 6352 (class 2606 OID 26971)
-- Name: helipad helipad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.helipad
    ADD CONSTRAINT helipad_pkey PRIMARY KEY (gid);


--
-- TOC entry 6355 (class 2606 OID 26983)
-- Name: islamabad islamabad_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.islamabad
    ADD CONSTRAINT islamabad_pkey PRIMARY KEY (gid);


--
-- TOC entry 6449 (class 2606 OID 36583)
-- Name: landuse landuse_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.landuse
    ADD CONSTRAINT landuse_pkey PRIMARY KEY (rid);


--
-- TOC entry 6429 (class 2606 OID 27240)
-- Name: maps_bank maps_bank_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.maps_bank
    ADD CONSTRAINT maps_bank_pkey PRIMARY KEY (id);


--
-- TOC entry 6432 (class 2606 OID 27248)
-- Name: maps_bus_stops maps_bus_stops_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.maps_bus_stops
    ADD CONSTRAINT maps_bus_stops_pkey PRIMARY KEY (id);


--
-- TOC entry 6435 (class 2606 OID 27256)
-- Name: maps_healthcare maps_healthcare_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.maps_healthcare
    ADD CONSTRAINT maps_healthcare_pkey PRIMARY KEY (id);


--
-- TOC entry 6438 (class 2606 OID 27264)
-- Name: maps_islamabad maps_islamabad_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.maps_islamabad
    ADD CONSTRAINT maps_islamabad_pkey PRIMARY KEY (id);


--
-- TOC entry 6441 (class 2606 OID 27272)
-- Name: maps_masjids maps_masjids_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.maps_masjids
    ADD CONSTRAINT maps_masjids_pkey PRIMARY KEY (id);


--
-- TOC entry 6444 (class 2606 OID 27280)
-- Name: maps_railway_station maps_railway_station_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.maps_railway_station
    ADD CONSTRAINT maps_railway_station_pkey PRIMARY KEY (id);


--
-- TOC entry 6447 (class 2606 OID 27288)
-- Name: maps_schoolst maps_schoolst_pkey; Type: CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.maps_schoolst
    ADD CONSTRAINT maps_schoolst_pkey PRIMARY KEY (id);


--
-- TOC entry 6358 (class 2606 OID 26992)
-- Name: masjids masjids_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.masjids
    ADD CONSTRAINT masjids_pkey PRIMARY KEY (gid);


--
-- TOC entry 6361 (class 2606 OID 27003)
-- Name: pois pois_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pois
    ADD CONSTRAINT pois_pkey PRIMARY KEY (gid);


--
-- TOC entry 6459 (class 2606 OID 43525)
-- Name: railway railway_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.railway
    ADD CONSTRAINT railway_pkey PRIMARY KEY (gid);


--
-- TOC entry 6364 (class 2606 OID 27017)
-- Name: railway_station railway_station_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.railway_station
    ADD CONSTRAINT railway_station_pkey PRIMARY KEY (gid);


--
-- TOC entry 6462 (class 2606 OID 43536)
-- Name: roads roads_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.roads
    ADD CONSTRAINT roads_pkey PRIMARY KEY (gid);


--
-- TOC entry 6367 (class 2606 OID 27027)
-- Name: schools schoolst_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.schools
    ADD CONSTRAINT schoolst_pkey PRIMARY KEY (gid);


--
-- TOC entry 6452 (class 2606 OID 36735)
-- Name: slope slope_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.slope
    ADD CONSTRAINT slope_pkey PRIMARY KEY (rid);


--
-- TOC entry 6370 (class 2606 OID 27039)
-- Name: transport transport_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.transport
    ADD CONSTRAINT transport_pkey PRIMARY KEY (gid);


--
-- TOC entry 6456 (class 2606 OID 43512)
-- Name: waters waters_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.waters
    ADD CONSTRAINT waters_pkey PRIMARY KEY (gid);


--
-- TOC entry 6382 (class 1259 OID 27196)
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- TOC entry 6387 (class 1259 OID 27137)
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- TOC entry 6390 (class 1259 OID 27138)
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- TOC entry 6377 (class 1259 OID 27123)
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- TOC entry 6398 (class 1259 OID 27153)
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- TOC entry 6401 (class 1259 OID 27152)
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- TOC entry 6404 (class 1259 OID 27167)
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- TOC entry 6407 (class 1259 OID 27166)
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- TOC entry 6395 (class 1259 OID 27191)
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- TOC entry 6341 (class 1259 OID 43458)
-- Name: bank_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bank_geom_idx ON public.bank USING gist (geom);


--
-- TOC entry 6344 (class 1259 OID 43490)
-- Name: bus_stops_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX bus_stops_geom_idx ON public.bus_stops USING gist (geom);


--
-- TOC entry 6410 (class 1259 OID 27187)
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- TOC entry 6413 (class 1259 OID 27188)
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- TOC entry 6423 (class 1259 OID 27232)
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- TOC entry 6426 (class 1259 OID 27231)
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- TOC entry 6414 (class 1259 OID 27221)
-- Name: gisapp_healthcare_geom_e865efdb_id; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX gisapp_healthcare_geom_e865efdb_id ON public.gisapp_healthcare USING gist (geom);


--
-- TOC entry 6417 (class 1259 OID 27222)
-- Name: gisapp_islamabadboundary_geom_008ff6c4_id; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX gisapp_islamabadboundary_geom_008ff6c4_id ON public.gisapp_islamabadboundary USING gist (geom);


--
-- TOC entry 6420 (class 1259 OID 27223)
-- Name: gisapp_school_geom_48b03581_id; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX gisapp_school_geom_48b03581_id ON public.gisapp_school USING gist (geom);


--
-- TOC entry 6347 (class 1259 OID 43442)
-- Name: healthcare_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX healthcare_geom_idx ON public.healthcare USING gist (geom);


--
-- TOC entry 6350 (class 1259 OID 43498)
-- Name: helipad_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX helipad_geom_idx ON public.helipad USING gist (geom);


--
-- TOC entry 6353 (class 1259 OID 27308)
-- Name: islamabad_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX islamabad_geom_idx ON public.islamabad USING gist (geom);


--
-- TOC entry 6450 (class 1259 OID 36587)
-- Name: landuse_st_convexhull_idx; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX landuse_st_convexhull_idx ON public.landuse USING gist (public.st_convexhull(rast));


--
-- TOC entry 6427 (class 1259 OID 27289)
-- Name: maps_bank_geom_59ac7611_id; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX maps_bank_geom_59ac7611_id ON public.maps_bank USING gist (geom);


--
-- TOC entry 6430 (class 1259 OID 27290)
-- Name: maps_bus_stops_geom_82b1ff5e_id; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX maps_bus_stops_geom_82b1ff5e_id ON public.maps_bus_stops USING gist (geom);


--
-- TOC entry 6433 (class 1259 OID 27291)
-- Name: maps_healthcare_geom_dd784a1e_id; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX maps_healthcare_geom_dd784a1e_id ON public.maps_healthcare USING gist (geom);


--
-- TOC entry 6436 (class 1259 OID 27292)
-- Name: maps_islamabad_geom_aa1776a0_id; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX maps_islamabad_geom_aa1776a0_id ON public.maps_islamabad USING gist (geom);


--
-- TOC entry 6439 (class 1259 OID 27293)
-- Name: maps_masjids_geom_873fc7a2_id; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX maps_masjids_geom_873fc7a2_id ON public.maps_masjids USING gist (geom);


--
-- TOC entry 6442 (class 1259 OID 27294)
-- Name: maps_railway_station_geom_58582418_id; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX maps_railway_station_geom_58582418_id ON public.maps_railway_station USING gist (geom);


--
-- TOC entry 6445 (class 1259 OID 27295)
-- Name: maps_schoolst_geom_b4bb128d_id; Type: INDEX; Schema: public; Owner: gisuser
--

CREATE INDEX maps_schoolst_geom_b4bb128d_id ON public.maps_schoolst USING gist (geom);


--
-- TOC entry 6356 (class 1259 OID 43474)
-- Name: masjids_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX masjids_geom_idx ON public.masjids USING gist (geom);


--
-- TOC entry 6359 (class 1259 OID 27006)
-- Name: pois_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pois_geom_idx ON public.pois USING gist (geom);


--
-- TOC entry 6457 (class 1259 OID 43577)
-- Name: railway_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX railway_geom_idx ON public.railway USING gist (geom);


--
-- TOC entry 6362 (class 1259 OID 43466)
-- Name: railway_station_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX railway_station_geom_idx ON public.railway_station USING gist (geom);


--
-- TOC entry 6460 (class 1259 OID 43563)
-- Name: roads_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX roads_geom_idx ON public.roads USING gist (geom);


--
-- TOC entry 6365 (class 1259 OID 43450)
-- Name: schoolst_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX schoolst_geom_idx ON public.schools USING gist (geom);


--
-- TOC entry 6453 (class 1259 OID 36739)
-- Name: slope_st_convexhull_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX slope_st_convexhull_idx ON public.slope USING gist (public.st_convexhull(rast));


--
-- TOC entry 6368 (class 1259 OID 43482)
-- Name: transport_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX transport_geom_idx ON public.transport USING gist (geom);


--
-- TOC entry 6454 (class 1259 OID 43585)
-- Name: waters_geom_idx; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX waters_geom_idx ON public.waters USING gist (geom);


--
-- TOC entry 6464 (class 2606 OID 27132)
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6465 (class 2606 OID 27127)
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6463 (class 2606 OID 27118)
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6466 (class 2606 OID 27147)
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6467 (class 2606 OID 27142)
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6468 (class 2606 OID 27161)
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6469 (class 2606 OID 27156)
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6470 (class 2606 OID 27177)
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6471 (class 2606 OID 27182)
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: gisuser
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- TOC entry 6629 (class 0 OID 0)
-- Dependencies: 227
-- Name: TABLE bank; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.bank TO gisuser;


--
-- TOC entry 6631 (class 0 OID 0)
-- Dependencies: 226
-- Name: SEQUENCE bank_gid_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.bank_gid_seq TO gisuser;


--
-- TOC entry 6632 (class 0 OID 0)
-- Dependencies: 229
-- Name: TABLE bus_stops; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.bus_stops TO gisuser;


--
-- TOC entry 6634 (class 0 OID 0)
-- Dependencies: 228
-- Name: SEQUENCE bus_stops_gid_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.bus_stops_gid_seq TO gisuser;


--
-- TOC entry 6635 (class 0 OID 0)
-- Dependencies: 231
-- Name: TABLE healthcare; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.healthcare TO gisuser;


--
-- TOC entry 6637 (class 0 OID 0)
-- Dependencies: 230
-- Name: SEQUENCE healthcare_gid_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.healthcare_gid_seq TO gisuser;


--
-- TOC entry 6638 (class 0 OID 0)
-- Dependencies: 233
-- Name: TABLE helipad; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.helipad TO gisuser;


--
-- TOC entry 6640 (class 0 OID 0)
-- Dependencies: 232
-- Name: SEQUENCE helipad_gid_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.helipad_gid_seq TO gisuser;


--
-- TOC entry 6641 (class 0 OID 0)
-- Dependencies: 235
-- Name: TABLE islamabad; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.islamabad TO gisuser;


--
-- TOC entry 6643 (class 0 OID 0)
-- Dependencies: 234
-- Name: SEQUENCE islamabad_gid_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.islamabad_gid_seq TO gisuser;


--
-- TOC entry 6645 (class 0 OID 0)
-- Dependencies: 237
-- Name: TABLE masjids; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.masjids TO gisuser;


--
-- TOC entry 6647 (class 0 OID 0)
-- Dependencies: 236
-- Name: SEQUENCE masjids_gid_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.masjids_gid_seq TO gisuser;


--
-- TOC entry 6648 (class 0 OID 0)
-- Dependencies: 239
-- Name: TABLE pois; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.pois TO gisuser;


--
-- TOC entry 6650 (class 0 OID 0)
-- Dependencies: 238
-- Name: SEQUENCE pois_gid_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.pois_gid_seq TO gisuser;


--
-- TOC entry 6651 (class 0 OID 0)
-- Dependencies: 305
-- Name: TABLE railway; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.railway TO gisuser;


--
-- TOC entry 6653 (class 0 OID 0)
-- Dependencies: 241
-- Name: TABLE railway_station; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.railway_station TO gisuser;


--
-- TOC entry 6655 (class 0 OID 0)
-- Dependencies: 240
-- Name: SEQUENCE railway_station_gid_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.railway_station_gid_seq TO gisuser;


--
-- TOC entry 6656 (class 0 OID 0)
-- Dependencies: 307
-- Name: TABLE roads; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.roads TO gisuser;


--
-- TOC entry 6658 (class 0 OID 0)
-- Dependencies: 243
-- Name: TABLE schools; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.schools TO gisuser;


--
-- TOC entry 6660 (class 0 OID 0)
-- Dependencies: 242
-- Name: SEQUENCE schoolst_gid_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.schoolst_gid_seq TO gisuser;


--
-- TOC entry 6661 (class 0 OID 0)
-- Dependencies: 298
-- Name: TABLE slope; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.slope TO gisuser;


--
-- TOC entry 6663 (class 0 OID 0)
-- Dependencies: 245
-- Name: TABLE transport; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.transport TO gisuser;


--
-- TOC entry 6665 (class 0 OID 0)
-- Dependencies: 244
-- Name: SEQUENCE transport_gid_seq; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON SEQUENCE public.transport_gid_seq TO gisuser;


--
-- TOC entry 6666 (class 0 OID 0)
-- Dependencies: 303
-- Name: TABLE waters; Type: ACL; Schema: public; Owner: postgres
--

GRANT ALL ON TABLE public.waters TO gisuser;


-- Completed on 2025-04-10 16:53:26

--
-- PostgreSQL database dump complete
--

